title: My Outreachy Blog
description: A blog documenting my journey with Outreachy and Mozilla Firefox
baseurl: "/outreachyXfirefox"
url: "https://ananyashreesharma.github.io"
plugins:
  - jekyll-feed

